---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - service
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - service/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - service/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - inference.x-k8s.io
  resources:
  - LLMRoutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inference.x-k8s.io
  resources:
  - LLMRoutes/finalizers
  verbs:
  - update
- apiGroups:
  - inference.x-k8s.io
  resources:
  - LLMRoutes/status
  verbs:
  - get
  - patch
  - update
