
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vllm-route
  namespace: default
spec:
  parentRefs:
  - name: example-gateway
  rules:
  - backendRefs:
    - name: grpc-envoy-lora
      port: 80
      kind: Service
    timeouts:
      request: "1000s"
      backendRequest: "1000s"