apiVersion: v1
kind: Namespace
metadata:
  name: llm-gateway

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: llm-route-envoy-config
  namespace: llm-gateway
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        patch:
          type: StrategicMerge
          value:
            spec:
              ports:
                - name: http-8081
                  port: 8081
                  protocol: TCP
                  targetPort: 8081
  bootstrap:
    type: Merge 
    value: |
      static_resources:
        listeners:
          - name: listener_0
            address:
              socket_address:
                address: 0.0.0.0
                port_value: 8081
            filter_chains:
              - filters:
                  - name: envoy.filters.network.http_connection_manager
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                      stat_prefix: http
                      codec_type: AUTO
                      route_config:
                        name: local_route
                        virtual_hosts:      
                          - name: backend
                            domains: ["*"]
                            routes:
                              - match:
                                  prefix: "/"
                                route:  
                                  cluster: original_destination_cluster
                                  timeout: 1000s  # Increase route timeout
                      http_filters:
                        - name: envoy.filters.http.ext_proc
                          typed_config:
                            "@type": type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor
                            failure_mode_allow: false
                            grpc_service:
                              envoy_grpc:
                                cluster_name: ext_proc_cluster
                            processing_mode:
                              request_header_mode: "SEND"
                              response_header_mode: "SEND"
                              request_body_mode: "BUFFERED"
                              response_body_mode: "NONE"
                              request_trailer_mode: "SKIP"
                              response_trailer_mode: "SKIP"
                        - name: envoy.filters.http.router
                          typed_config:
                            "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
        clusters:
          - name: original_destination_cluster
            type: ORIGINAL_DST
            original_dst_lb_config:
              use_http_header: true
              http_header_name: "target-pod"
            connect_timeout: 6s
            lb_policy: CLUSTER_PROVIDED
            dns_lookup_family: V4_ONLY
          - name: ext_proc_cluster
            connect_timeout: 1000s
            type: LOGICAL_DNS
            http2_protocol_options: {}
            lb_policy: ROUND_ROBIN
            load_assignment:
              cluster_name: ext_proc_cluster
              endpoints:
                - lb_endpoints:
                    - endpoint:
                        address:
                          socket_address:
                            address: llm-route-ext-proc.llm-gateway.svc.cluster.local
                            port_value: 9002
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: llm-gateway
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:  
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: llm-route-envoy-config
    namespace: llm-gateway

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-route-ext-proc
  namespace: llm-gateway
  labels:
    app: llm-route-ext-proc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-route-ext-proc
  template:
    metadata:
      labels:
        app: llm-route-ext-proc
    spec:
      containers:
      - name: llm-route-ext-proc
        image: ghcr.io/tomatillo-and-multiverse/ext-proc:demo
        args:
        #TODO: specify label selector and dynamically update pods
        - -pods
        - "vllm-78665f78c4-h4kx4,vllm-78665f78c4-hnz84"
        - -podIPs
        - "10.24.11.6:8000,10.24.5.7:8000"
        - -enable-fairness
        - "false"
        ports:
        - containerPort: 9002
      - name: curl
        image: curlimages/curl
        command: ["sleep", "3600"]
---
apiVersion: v1
kind: Service
metadata:
  name: llm-route-ext-proc
  namespace: llm-gateway
spec:
  selector:
    app: llm-route-ext-proc
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002
  type: ClusterIP
