
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: genai-inference-gateway
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: custom-proxy-config
    namespace: envoy-gateway-system

---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: genai-inference-gateway
spec:
  gatewayClassName: genai-inference-gateway
  listeners:
    - name: http
      protocol: HTTP
      port: 80
