# permissions for end users to view loraroutes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: lora
    app.kubernetes.io/managed-by: kustomize
  name: loraroute-viewer-role
rules:
- apiGroups:
  - inference.x-k8s.io
  resources:
  - loraroutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - inference.x-k8s.io
  resources:
  - loraroutes/status
  verbs:
  - get
